apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240610185442.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240610185442.0.0+build.6aff574
  releaseNotes: |
    Release v20240610185442.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-10-06-2024-13-55-27-996471846/where-for-dinner-my-apps-bundle@sha256:94c6d8944f353f745c8d972313b0c9232e2b66c91b3297d1be71bcf8f236cf4c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

