apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240610185512.0.0+build.6aff574
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240610185512.0.0+build.6aff574
  releaseNotes: |
    Release v20240610185512.0.0+build.6aff574 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-10-06-2024-13-55-27-996471846/where-for-dinner-availability-my-apps-bundle@sha256:254d0fce73fde89f44d5a2da74b18f2801832902ef4128ef1012c4c77bbb911e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

