apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240610185546.0.0+build.6aff574
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240610185546.0.0+build.6aff574
  releaseNotes: |
    Release v20240610185546.0.0+build.6aff574 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-10-06-2024-13-55-27-996471846/where-for-dinner-notify-my-apps-bundle@sha256:59e50fcb7b504e560475670a4e364ca63c281d0fa13e6190b2e0d5791c9ca1bb
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

